# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pc/repos/Runner

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pc/repos/Runner

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pc/repos/Runner/CMakeFiles /home/pc/repos/Runner/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pc/repos/Runner/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Runner

# Build rule for target.
Runner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Runner
.PHONY : Runner

# fast build rule for target.
Runner/fast:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/build
.PHONY : Runner/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f external/glfw/src/CMakeFiles/glfw.dir/build.make external/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) -f external/glfw/src/CMakeFiles/update_mappings.dir/build.make external/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

#=============================================================================
# Target rules for targets named glad-generate-files

# Build rule for target.
glad-generate-files: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glad-generate-files
.PHONY : glad-generate-files

# fast build rule for target.
glad-generate-files/fast:
	$(MAKE) -f external/glad/CMakeFiles/glad-generate-files.dir/build.make external/glad/CMakeFiles/glad-generate-files.dir/build
.PHONY : glad-generate-files/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) -f external/glad/CMakeFiles/glad.dir/build.make external/glad/CMakeFiles/glad.dir/build
.PHONY : glad/fast

sources/Camera.o: sources/Camera.cpp.o

.PHONY : sources/Camera.o

# target to build an object file
sources/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/Camera.cpp.o
.PHONY : sources/Camera.cpp.o

sources/Camera.i: sources/Camera.cpp.i

.PHONY : sources/Camera.i

# target to preprocess a source file
sources/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/Camera.cpp.i
.PHONY : sources/Camera.cpp.i

sources/Camera.s: sources/Camera.cpp.s

.PHONY : sources/Camera.s

# target to generate assembly for a file
sources/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/Camera.cpp.s
.PHONY : sources/Camera.cpp.s

sources/CollisionBox.o: sources/CollisionBox.cpp.o

.PHONY : sources/CollisionBox.o

# target to build an object file
sources/CollisionBox.cpp.o:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/CollisionBox.cpp.o
.PHONY : sources/CollisionBox.cpp.o

sources/CollisionBox.i: sources/CollisionBox.cpp.i

.PHONY : sources/CollisionBox.i

# target to preprocess a source file
sources/CollisionBox.cpp.i:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/CollisionBox.cpp.i
.PHONY : sources/CollisionBox.cpp.i

sources/CollisionBox.s: sources/CollisionBox.cpp.s

.PHONY : sources/CollisionBox.s

# target to generate assembly for a file
sources/CollisionBox.cpp.s:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/CollisionBox.cpp.s
.PHONY : sources/CollisionBox.cpp.s

sources/Container.o: sources/Container.cpp.o

.PHONY : sources/Container.o

# target to build an object file
sources/Container.cpp.o:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/Container.cpp.o
.PHONY : sources/Container.cpp.o

sources/Container.i: sources/Container.cpp.i

.PHONY : sources/Container.i

# target to preprocess a source file
sources/Container.cpp.i:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/Container.cpp.i
.PHONY : sources/Container.cpp.i

sources/Container.s: sources/Container.cpp.s

.PHONY : sources/Container.s

# target to generate assembly for a file
sources/Container.cpp.s:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/Container.cpp.s
.PHONY : sources/Container.cpp.s

sources/FileLoader.o: sources/FileLoader.cpp.o

.PHONY : sources/FileLoader.o

# target to build an object file
sources/FileLoader.cpp.o:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/FileLoader.cpp.o
.PHONY : sources/FileLoader.cpp.o

sources/FileLoader.i: sources/FileLoader.cpp.i

.PHONY : sources/FileLoader.i

# target to preprocess a source file
sources/FileLoader.cpp.i:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/FileLoader.cpp.i
.PHONY : sources/FileLoader.cpp.i

sources/FileLoader.s: sources/FileLoader.cpp.s

.PHONY : sources/FileLoader.s

# target to generate assembly for a file
sources/FileLoader.cpp.s:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/FileLoader.cpp.s
.PHONY : sources/FileLoader.cpp.s

sources/Material.o: sources/Material.cpp.o

.PHONY : sources/Material.o

# target to build an object file
sources/Material.cpp.o:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/Material.cpp.o
.PHONY : sources/Material.cpp.o

sources/Material.i: sources/Material.cpp.i

.PHONY : sources/Material.i

# target to preprocess a source file
sources/Material.cpp.i:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/Material.cpp.i
.PHONY : sources/Material.cpp.i

sources/Material.s: sources/Material.cpp.s

.PHONY : sources/Material.s

# target to generate assembly for a file
sources/Material.cpp.s:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/Material.cpp.s
.PHONY : sources/Material.cpp.s

sources/Mesh.o: sources/Mesh.cpp.o

.PHONY : sources/Mesh.o

# target to build an object file
sources/Mesh.cpp.o:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/Mesh.cpp.o
.PHONY : sources/Mesh.cpp.o

sources/Mesh.i: sources/Mesh.cpp.i

.PHONY : sources/Mesh.i

# target to preprocess a source file
sources/Mesh.cpp.i:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/Mesh.cpp.i
.PHONY : sources/Mesh.cpp.i

sources/Mesh.s: sources/Mesh.cpp.s

.PHONY : sources/Mesh.s

# target to generate assembly for a file
sources/Mesh.cpp.s:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/Mesh.cpp.s
.PHONY : sources/Mesh.cpp.s

sources/PointLight.o: sources/PointLight.cpp.o

.PHONY : sources/PointLight.o

# target to build an object file
sources/PointLight.cpp.o:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/PointLight.cpp.o
.PHONY : sources/PointLight.cpp.o

sources/PointLight.i: sources/PointLight.cpp.i

.PHONY : sources/PointLight.i

# target to preprocess a source file
sources/PointLight.cpp.i:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/PointLight.cpp.i
.PHONY : sources/PointLight.cpp.i

sources/PointLight.s: sources/PointLight.cpp.s

.PHONY : sources/PointLight.s

# target to generate assembly for a file
sources/PointLight.cpp.s:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/PointLight.cpp.s
.PHONY : sources/PointLight.cpp.s

sources/ScoreCounter.o: sources/ScoreCounter.cpp.o

.PHONY : sources/ScoreCounter.o

# target to build an object file
sources/ScoreCounter.cpp.o:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/ScoreCounter.cpp.o
.PHONY : sources/ScoreCounter.cpp.o

sources/ScoreCounter.i: sources/ScoreCounter.cpp.i

.PHONY : sources/ScoreCounter.i

# target to preprocess a source file
sources/ScoreCounter.cpp.i:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/ScoreCounter.cpp.i
.PHONY : sources/ScoreCounter.cpp.i

sources/ScoreCounter.s: sources/ScoreCounter.cpp.s

.PHONY : sources/ScoreCounter.s

# target to generate assembly for a file
sources/ScoreCounter.cpp.s:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/ScoreCounter.cpp.s
.PHONY : sources/ScoreCounter.cpp.s

sources/ShaderProgram.o: sources/ShaderProgram.cpp.o

.PHONY : sources/ShaderProgram.o

# target to build an object file
sources/ShaderProgram.cpp.o:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/ShaderProgram.cpp.o
.PHONY : sources/ShaderProgram.cpp.o

sources/ShaderProgram.i: sources/ShaderProgram.cpp.i

.PHONY : sources/ShaderProgram.i

# target to preprocess a source file
sources/ShaderProgram.cpp.i:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/ShaderProgram.cpp.i
.PHONY : sources/ShaderProgram.cpp.i

sources/ShaderProgram.s: sources/ShaderProgram.cpp.s

.PHONY : sources/ShaderProgram.s

# target to generate assembly for a file
sources/ShaderProgram.cpp.s:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/ShaderProgram.cpp.s
.PHONY : sources/ShaderProgram.cpp.s

sources/Texture2D.o: sources/Texture2D.cpp.o

.PHONY : sources/Texture2D.o

# target to build an object file
sources/Texture2D.cpp.o:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/Texture2D.cpp.o
.PHONY : sources/Texture2D.cpp.o

sources/Texture2D.i: sources/Texture2D.cpp.i

.PHONY : sources/Texture2D.i

# target to preprocess a source file
sources/Texture2D.cpp.i:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/Texture2D.cpp.i
.PHONY : sources/Texture2D.cpp.i

sources/Texture2D.s: sources/Texture2D.cpp.s

.PHONY : sources/Texture2D.s

# target to generate assembly for a file
sources/Texture2D.cpp.s:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/Texture2D.cpp.s
.PHONY : sources/Texture2D.cpp.s

sources/ThirdPersonCamera.o: sources/ThirdPersonCamera.cpp.o

.PHONY : sources/ThirdPersonCamera.o

# target to build an object file
sources/ThirdPersonCamera.cpp.o:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/ThirdPersonCamera.cpp.o
.PHONY : sources/ThirdPersonCamera.cpp.o

sources/ThirdPersonCamera.i: sources/ThirdPersonCamera.cpp.i

.PHONY : sources/ThirdPersonCamera.i

# target to preprocess a source file
sources/ThirdPersonCamera.cpp.i:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/ThirdPersonCamera.cpp.i
.PHONY : sources/ThirdPersonCamera.cpp.i

sources/ThirdPersonCamera.s: sources/ThirdPersonCamera.cpp.s

.PHONY : sources/ThirdPersonCamera.s

# target to generate assembly for a file
sources/ThirdPersonCamera.cpp.s:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/ThirdPersonCamera.cpp.s
.PHONY : sources/ThirdPersonCamera.cpp.s

sources/Transform.o: sources/Transform.cpp.o

.PHONY : sources/Transform.o

# target to build an object file
sources/Transform.cpp.o:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/Transform.cpp.o
.PHONY : sources/Transform.cpp.o

sources/Transform.i: sources/Transform.cpp.i

.PHONY : sources/Transform.i

# target to preprocess a source file
sources/Transform.cpp.i:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/Transform.cpp.i
.PHONY : sources/Transform.cpp.i

sources/Transform.s: sources/Transform.cpp.s

.PHONY : sources/Transform.s

# target to generate assembly for a file
sources/Transform.cpp.s:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/Transform.cpp.s
.PHONY : sources/Transform.cpp.s

sources/WavefrontReader.o: sources/WavefrontReader.cpp.o

.PHONY : sources/WavefrontReader.o

# target to build an object file
sources/WavefrontReader.cpp.o:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/WavefrontReader.cpp.o
.PHONY : sources/WavefrontReader.cpp.o

sources/WavefrontReader.i: sources/WavefrontReader.cpp.i

.PHONY : sources/WavefrontReader.i

# target to preprocess a source file
sources/WavefrontReader.cpp.i:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/WavefrontReader.cpp.i
.PHONY : sources/WavefrontReader.cpp.i

sources/WavefrontReader.s: sources/WavefrontReader.cpp.s

.PHONY : sources/WavefrontReader.s

# target to generate assembly for a file
sources/WavefrontReader.cpp.s:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/WavefrontReader.cpp.s
.PHONY : sources/WavefrontReader.cpp.s

sources/extra.o: sources/extra.cpp.o

.PHONY : sources/extra.o

# target to build an object file
sources/extra.cpp.o:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/extra.cpp.o
.PHONY : sources/extra.cpp.o

sources/extra.i: sources/extra.cpp.i

.PHONY : sources/extra.i

# target to preprocess a source file
sources/extra.cpp.i:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/extra.cpp.i
.PHONY : sources/extra.cpp.i

sources/extra.s: sources/extra.cpp.s

.PHONY : sources/extra.s

# target to generate assembly for a file
sources/extra.cpp.s:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/extra.cpp.s
.PHONY : sources/extra.cpp.s

sources/main.o: sources/main.cpp.o

.PHONY : sources/main.o

# target to build an object file
sources/main.cpp.o:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/main.cpp.o
.PHONY : sources/main.cpp.o

sources/main.i: sources/main.cpp.i

.PHONY : sources/main.i

# target to preprocess a source file
sources/main.cpp.i:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/main.cpp.i
.PHONY : sources/main.cpp.i

sources/main.s: sources/main.cpp.s

.PHONY : sources/main.s

# target to generate assembly for a file
sources/main.cpp.s:
	$(MAKE) -f CMakeFiles/Runner.dir/build.make CMakeFiles/Runner.dir/sources/main.cpp.s
.PHONY : sources/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Runner"
	@echo "... edit_cache"
	@echo "... glfw"
	@echo "... update_mappings"
	@echo "... glad-generate-files"
	@echo "... glad"
	@echo "... sources/Camera.o"
	@echo "... sources/Camera.i"
	@echo "... sources/Camera.s"
	@echo "... sources/CollisionBox.o"
	@echo "... sources/CollisionBox.i"
	@echo "... sources/CollisionBox.s"
	@echo "... sources/Container.o"
	@echo "... sources/Container.i"
	@echo "... sources/Container.s"
	@echo "... sources/FileLoader.o"
	@echo "... sources/FileLoader.i"
	@echo "... sources/FileLoader.s"
	@echo "... sources/Material.o"
	@echo "... sources/Material.i"
	@echo "... sources/Material.s"
	@echo "... sources/Mesh.o"
	@echo "... sources/Mesh.i"
	@echo "... sources/Mesh.s"
	@echo "... sources/PointLight.o"
	@echo "... sources/PointLight.i"
	@echo "... sources/PointLight.s"
	@echo "... sources/ScoreCounter.o"
	@echo "... sources/ScoreCounter.i"
	@echo "... sources/ScoreCounter.s"
	@echo "... sources/ShaderProgram.o"
	@echo "... sources/ShaderProgram.i"
	@echo "... sources/ShaderProgram.s"
	@echo "... sources/Texture2D.o"
	@echo "... sources/Texture2D.i"
	@echo "... sources/Texture2D.s"
	@echo "... sources/ThirdPersonCamera.o"
	@echo "... sources/ThirdPersonCamera.i"
	@echo "... sources/ThirdPersonCamera.s"
	@echo "... sources/Transform.o"
	@echo "... sources/Transform.i"
	@echo "... sources/Transform.s"
	@echo "... sources/WavefrontReader.o"
	@echo "... sources/WavefrontReader.i"
	@echo "... sources/WavefrontReader.s"
	@echo "... sources/extra.o"
	@echo "... sources/extra.i"
	@echo "... sources/extra.s"
	@echo "... sources/main.o"
	@echo "... sources/main.i"
	@echo "... sources/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

